apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-priority-manager
  namespace: kube-priority-manager-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-priority-manager
