apiVersion: v1
kind: Service
metadata:
  name: kube-priority-webhook
  namespace: kube-priority-system
  labels:
    app.kubernetes.io/name: kube-priority
spec:
  selector:
    app.kubernetes.io/name: kube-priority
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: kube-priority-metrics
  namespace: kube-priority-system
  labels:
    app.kubernetes.io/name: kube-priority
spec:
  selector:
    app.kubernetes.io/name: kube-priority
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
