apiVersion: v1
kind: Service
metadata:
  name: kube-priority-manager-webhook
  namespace: kube-priority-manager-system
  labels:
    app.kubernetes.io/name: kube-priority-manager
spec:
  selector:
    app.kubernetes.io/name: kube-priority-manager
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: kube-priority-manager-metrics
  namespace: kube-priority-manager-system
  labels:
    app.kubernetes.io/name: kube-priority-manager
spec:
  selector:
    app.kubernetes.io/name: kube-priority-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
