{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-priority
  namespace: {{ include "kube-priority.namespace" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels: { app.kubernetes.io/name: kube-priority }
{{- end }}
